Repository fac-17/FFFF, pull requests merged in 2019-09, with the labels that each got.

#52 set up view engine
  src/app.js
Labels: blocker, server

#50 Set up
  .eslintrc.js
  .travis.yml
  package.json
  src/tests/db.test.js
  src/tests/router.tests.js
Labels: blocker, setup, testing

#51 Folders and file structure setup
  public/assets/placeholder_aubergine.jpg
  public/css/style.css
  public/js/main.js
  src/controllers/index.js
  src/model/index.js
  src/views/error.hbs
  src/views/helpers/index.js
  src/views/layouts/error.hbs
  src/views/layouts/main.hbs
  src/views/partials/header.hbs
Labels: blocker, setup

#54 Feature/env setup
  src/app.js
Labels: blocker, db, setup

#55 Setup/basic db setup
  src/model/database/db_build.js
  src/model/database/db_build.sql
  src/model/database/db_connection.js
  src/model/database/db_init.js
Labels: db

#56 Setup/db build sql
  src/app.js
  src/model/database/db_build.sql
  src/tests/router.tests.js
Labels: blocker, db

#59 Feature/route select
  src/app.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/select.js
  src/tests/router.tests.js
Labels: server

#63 Db testing
  package-lock.json
  package.json
  src/model/queries/findQueries.js
  src/tests/db.test.js
  src/tests/db.tests.js
Labels: db, testing

#95 Sass
  package.json
  public/css/select.css
  public/css/style.css
  public/sass/select.sass
  public/sass/style.sass
  src/controllers/select.js
  src/views/layouts/main.hbs
  src/views/partials/head.hbs
Labels: design

#106 Breakdown page
  src/controllers/itemsbysupermarket.js
  src/model/database/db_build.sql
  src/views/helpers/index.js
  src/views/itemsbysupermarket.hbs
  src/views/partials/header.hbs
  src/views/select.hbs
Labels: component, db, priority-1

#107 Error pages
  src/controllers/dummy.js
  src/controllers/error.js
  src/controllers/index.js
  src/tests/router.tests.js
  src/views/dummy.hbs
  src/views/error.hbs
  src/views/layouts/error.hbs
Labels: server, testing

#135 Add apostrophe to Sainsbury's name and tidy up DROP TABLE
  src/model/database/db_build.sql
Labels: bug

#145 Style/restyle results
  public/css/results.css
  public/css/style.css
  public/sass/_variables.sass
  public/sass/results.sass
  public/sass/style.sass
  src/views/helpers/index.js
  src/views/helpers/indexplusone.js
  src/views/results.hbs
Labels: style

#146 Breakdown fix
  public/css/itemsbysupermarket.css
  public/sass/itemsbysupermarket.sass
  public/sass/results.sass
  src/controllers/itemsbysupermarket.js
  src/tests/hbs.helpers.tests.js
  src/views/helpers/color.js
  src/views/helpers/index.js
  src/views/helpers/labels.js
  src/views/helpers/scorer.js
  src/views/itemsbysupermarket.hbs
  src/views/results.hbs
Labels: design

#150 fix the image too big on items by page
  public/sass/itemsbysupermarket.sass
  src/views/itemsbysupermarket.hbs
Labels: bug

#156 Feature/svg logo
  public/assets/vegetables.svg
  public/css/style.css
  public/sass/style.sass
  src/views/partials/header.hbs
Labels: design

#159 Fix/itemimagedistortion
  public/css/itemsbysupermarket.css
  public/sass/itemsbysupermarket.sass
  src/views/itemsbysupermarket.hbs
Labels: bug, design

#157 Feature/html page titles
  src/controllers/home.js
  src/controllers/itemsbysupermarket.js
  src/controllers/results.js
Labels: design

#163 remove text decoration Closes #161
  public/css/results.css
  public/sass/results.sass
Labels: design

#169 add some padding to the right and left Closes #165
  public/sass/results.sass
Labels: design

#168 Accessibility
  public/css/style.css
  public/js/shoppingSelection.js
  public/sass/style.sass
  src/views/home.hbs
  src/views/itemsbysupermarket.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  src/views/results.hbs
  src/views/select.hbs
Labels: bug, design, enhancement

#174 Style/fix digits dots
  public/css/home.css
  public/sass/home.sass
  src/views/home.hbs
Labels: bug, design

#179 Fix/recognise label
  public/css/results.css
  public/sass/results.sass
Labels: design

#192 coverage badge
  .travis.yml
  package-lock.json
  package.json
Labels: testing
